import { useState, useEffect } from 'react'
import api from '../api'
import { exportPDF, exportExcel, printTable, ExportBar } from '../utils/exportUtils'
import { isValidEmail, isValidPhone } from '../utils/validation'
import {
  Btn, Input, NumInput, Modal, Card, Badge, Empty,
  ConfirmModal, Table, FormGrid, PageHeader, SectionLabel, Icon, Spinner, SearchBar,
} from '../components/ui'

const empty = { companyName: '', representativeName: '', address: '', email: '', phone: '', openingBalance: '' }

const COLS = [
  { header: 'Code', accessor: r => r.company_code },
  { header: 'Company Name', accessor: r => r.company_name },
  { header: 'Representative', accessor: r => r.representative_name },
  { header: 'Phone', accessor: r => r.phone },
  { header: 'Email', accessor: r => r.email },
  { header: 'Address', accessor: r => r.address },
  { header: 'Opening Balance', accessor: r => `Rs. ${Number(r.opening_balance).toFixed(2)}` },
]

function VendorModal({ title, form, onChange, onSave, onClose, saving, isEdit }) {
  const [errors, setErrors] = useState({})
  const handleSave = () => {
    const errs = {}
    if (!isValidPhone(form.phone)) errs.phone = 'Invalid phone number (e.g. 0300-1234567)'
    if (!isValidEmail(form.email)) errs.email = 'Invalid email address'
    if (Object.keys(errs).length) { setErrors(errs); return }
    setErrors({})
    onSave()
  }
  return (
    <Modal open onClose={onClose} title={title}
      onKeyDown={e => { if (e.key === 'Enter') handleSave() }}
      footer={
        <>
          <Btn variant="secondary" onClick={onClose}>Cancel</Btn>
          <Btn variant="primary" onClick={handleSave} disabled={saving}>
            {saving ? 'Saving...' : 'Save'}
          </Btn>
        </>
      }
    >
      <FormGrid cols={2}>
        {isEdit ? (
          <div style={{ gridColumn: '1 / -1' }}>
            <Input label="Company Code" value={form.companyCode || ''} readOnly
              style={{ background: '#f8fafc', color: '#94a3b8', cursor: 'not-allowed' }} />
          </div>
        ) : (
          <div style={{ gridColumn: '1 / -1' }}>
            <label className="form-label" style={{ color: '#94a3b8' }}>Company Code</label>
            <div style={{ border: '1px dashed #cbd5e1', borderRadius: 8, padding: '8px 12px', color: '#94a3b8', fontSize: 13, background: '#f8fafc' }}>
              Auto-generated by system
            </div>
          </div>
        )}

        <div style={{ gridColumn: '1 / -1' }}>
          <Input label="Company Name" required value={form.companyName}
            onChange={e => onChange('companyName', e.target.value)}
            placeholder="Enter company name"
            autoFocus />
        </div>

        <div style={{ gridColumn: '1 / -1' }}>
          <Input label="Representative Name" value={form.representativeName}
            onChange={e => onChange('representativeName', e.target.value)}
            placeholder="Enter representative name" />
        </div>

        <Input label="Phone" value={form.phone}
          onChange={e => { onChange('phone', e.target.value); setErrors(p => ({ ...p, phone: '' })) }}
          placeholder="e.g. 0300-1234567"
          error={errors.phone} />

        <Input label="Email" type="email" value={form.email}
          onChange={e => { onChange('email', e.target.value); setErrors(p => ({ ...p, email: '' })) }}
          placeholder="e.g. info@company.com"
          error={errors.email} />

        <div style={{ gridColumn: '1 / -1' }}>
          <Input label="Address" value={form.address}
            onChange={e => onChange('address', e.target.value)}
            placeholder="Enter address" />
        </div>

        <div style={{ gridColumn: '1 / -1' }}>
          <NumInput label="Opening Balance" value={form.openingBalance || ''}
            onChange={e => onChange('openingBalance', Number(e.target.value))}
            placeholder="0.00" step="any" />
        </div>
      </FormGrid>
    </Modal>
  )
}

export default function Vendors() {
  const [vendors, setVendors] = useState([])
  const [loading, setLoading] = useState(true)
  const [modal, setModal] = useState(null)
  const [form, setForm] = useState(empty)
  const [saving, setSaving] = useState(false)
  const [search, setSearch] = useState('')
  const [deleteId, setDeleteId] = useState(null)

  const load = () => api.get('/vendors').then(r => { setVendors(r.data); setLoading(false) })
  useEffect(() => { load() }, [])

  useEffect(() => {
    const handler = (e) => {
      if ((e.key === 'n' || e.key === 'N') && !['INPUT', 'TEXTAREA', 'SELECT'].includes(e.target.tagName)) {
        openAdd()
      }
    }
    document.addEventListener('keydown', handler)
    return () => document.removeEventListener('keydown', handler)
  }, [])

  const openAdd = () => { setForm(empty); setModal('add') }
  const openEdit = (v) => {
    setForm({ companyCode: v.company_code, companyName: v.company_name, representativeName: v.representative_name || '', address: v.address || '', email: v.email || '', phone: v.phone || '', openingBalance: v.opening_balance })
    setModal(v.id)
  }

  const save = async () => {
    setSaving(true)
    try {
      if (modal === 'add') await api.post('/vendors', form)
      else await api.put(`/vendors/${modal}`, form)
      setModal(null); await load()
    } catch (e) { alert(e.response?.data?.error || 'Error saving') }
    setSaving(false)
  }

  const del = async (id) => {
    try { await api.delete(`/vendors/${id}`); setDeleteId(null); await load() }
    catch (e) { alert(e.response?.data?.error || 'Error deleting') }
  }

  const filtered = vendors.filter(v =>
    v.company_name?.toLowerCase().includes(search.toLowerCase()) ||
    v.company_code?.toLowerCase().includes(search.toLowerCase())
  )

  if (loading) return (
    <div style={{ padding: '48px 32px', display: 'flex', alignItems: 'center', gap: 10, color: '#94a3b8' }}>
      <Spinner size={20} /> Loading vendors…
    </div>
  )

  return (
    <div style={{ padding: '28px 32px', maxWidth: 1400 }}>

      <PageHeader
        title="Vendors"
        subtitle={`${vendors.length} registered vendors`}
        actions={
          <>
            <ExportBar
              onPDF={() => exportPDF('Vendors Report', COLS, filtered, 'vendors')}
              onExcel={() => exportExcel('Vendors Report', COLS, filtered, 'vendors')}
              onPrint={() => printTable('Vendors Report', COLS, filtered)}
            />
            <Btn variant="primary" onClick={openAdd} icon={<Icon.Plus style={{ width: 14, height: 14 }} />}>
              Add Vendor
            </Btn>
          </>
        }
      />

      <Card style={{ padding: 0 }}>
        <div style={{ padding: '12px 16px', borderBottom: '1px solid #e2e8f0', display: 'flex', gap: 10, alignItems: 'center' }}>
          <SearchBar
            value={search}
            onChange={e => setSearch(e.target.value)}
            placeholder="Search by company name or code..."
            style={{ width: 300 }}
          />
          {search && (
            <Btn variant="ghost" size="sm" onClick={() => setSearch('')}>Clear</Btn>
          )}
        </div>

        <Table>
          <thead>
            <tr>
              <th>Code</th>
              <th>Company Name</th>
              <th>Representative</th>
              <th>Phone</th>
              <th>Email</th>
              <th>Opening Bal.</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {filtered.length === 0 ? (
              <tr>
                <td colSpan={7}>
                  <Empty message={search ? 'No vendors match your search' : 'No vendors found'} hint="Click Add Vendor or press N to add one" />
                </td>
              </tr>
            ) : filtered.map(v => (
              <tr key={v.id}>
                <td style={{ fontFamily: 'monospace', fontSize: 11, color: '#64748b' }}>{v.company_code}</td>
                <td style={{ fontWeight: 500 }}>{v.company_name}</td>
                <td>{v.representative_name || <span style={{ color: '#cbd5e1' }}>—</span>}</td>
                <td>{v.phone || <span style={{ color: '#cbd5e1' }}>—</span>}</td>
                <td>{v.email || <span style={{ color: '#cbd5e1' }}>—</span>}</td>
                <td>Rs. {Number(v.opening_balance).toFixed(2)}</td>
                <td>
                  <div style={{ display: 'flex', gap: 4 }}>
                    <Btn variant="ghost" size="sm" onClick={() => openEdit(v)} title="Edit">
                      <Icon.Edit style={{ width: 14, height: 14 }} />
                    </Btn>
                    <Btn variant="ghost" size="sm" onClick={() => setDeleteId(v.id)} title="Delete" style={{ color: '#ef4444' }}>
                      <Icon.Trash style={{ width: 14, height: 14 }} />
                    </Btn>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </Table>
      </Card>

      {modal && (
        <VendorModal
          title={modal === 'add' ? 'Add Vendor' : 'Edit Vendor'}
          form={form}
          onChange={(k, v) => setForm(f => ({ ...f, [k]: v }))}
          onSave={save}
          onClose={() => setModal(null)}
          saving={saving}
          isEdit={modal !== 'add'}
        />
      )}

      <ConfirmModal
        open={!!deleteId}
        onClose={() => setDeleteId(null)}
        onConfirm={() => del(deleteId)}
        title="Delete Vendor"
        message="Are you sure you want to delete this vendor? This action cannot be undone."
        danger
      />
    </div>
  )
}
